### PR TITLE
Switch from Grpc.Core to Grpc.Net.Client

### LINKED ISSUE #751: Switch to new gRPC package
Per [this readme](https://github.com/grpc/grpc/tree/master/src/csharp#grpc-c) and [this blogpost](https://grpc.io/blog/grpc-csharp-future/), the `Grpc.Net.Client` nuget package is now the recommended gRPC implementation for .NET/C# as opposed to the `Grpc.Core` package. The old package is currently in maintenance mode and will be deprecated in May 2022

### PR DESCRIPTION
**Pull request by michaelpeng36**
### Issue describing the changes in this PR

resolves #751 to facilitate M1 compatibility for the PowerShell worker V4 using PowerShell 7.2.

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Comment by michaelpeng36** [comment]
I currently plan to backport this change to `v4.x/ps7.0` since `Grpc.Core` is to be deprecated in May 2022, and I anticipate we will still be doing releases of the PowerShell Worker at that point.

**Comment by michaelpeng36** [comment]
The changes in this PR are based on the changes implemented in the .NET worker (see [this](https://github.com/Azure/azure-functions-dotnet-worker/blob/3e65d91314fc0920349ecd5eaadc36162be868f3/src/DotNetWorker.Grpc/GrpcServiceCollectionExtensions.cs#L58) for the specific file). One difference here, however, is that `grpcUri` is a nullable `Uri` in the .NET worker. Do you think that is necessary here?

**Review by ejizba — APPROVED** [review]

**Review by Francisco-Gamino — APPROVED** [review]
LGTM

**Comment by Francisco-Gamino** [comment]
> The changes in this PR are based on the changes implemented in the .NET worker (see [this](https://github.com/Azure/azure-functions-dotnet-worker/blob/3e65d91314fc0920349ecd5eaadc36162be868f3/src/DotNetWorker.Grpc/GrpcServiceCollectionExtensions.cs#L58) for the specific file). One difference here, however, is that `grpcUri` is a nullable `Uri` in the .NET worker. Do you think that is necessary here?

I do not think so. You're current implementation works.

**Pull request merged**
