### PR TITLE
Switch from Grpc.Core to Grpc.Net.Client (#758)

### LINKED ISSUE #751: Switch to new gRPC package
Per [this readme](https://github.com/grpc/grpc/tree/master/src/csharp#grpc-c) and [this blogpost](https://grpc.io/blog/grpc-csharp-future/), the `Grpc.Net.Client` nuget package is now the recommended gRPC implementation for .NET/C# as opposed to the `Grpc.Core` package. The old package is currently in maintenance mode and will be deprecated in May 2022

### PR DESCRIPTION
**Pull request by michaelpeng36**
### Issue describing the changes in this PR

Cherry-pick of #758. Resolves #751 for `v4.x/ps7.0`.

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [x] My changes **should not** be added to the release notes for the next release
  * [ ] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

**Review by Francisco-Gamino — APPROVED** [review]
LGTM

**Comment by Francisco-Gamino** [comment]
Hello @michaelpeng36 -- We should get this change in by 6/1/22, so that this can be included in the next worker release and Functions deployment. Do you know if we need this change is needed for the Core Tools M1 build?

**Comment by ejizba** [comment]
Since this is targeting the 7.0 branch, it does _not_ matter for M1 support. PowerShell 7.2 was [the first](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2#installation-via-direct-download) version to support M1, and anything earlier won't work regardless of what we do on the Functions side

**Comment by Francisco-Gamino** [comment]
> Since this is targeting the 7.0 branch, it does _not_ matter for M1 support. PowerShell 7.2 was [the first](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-macos?view=powershell-7.2#installation-via-direct-download) version to support M1, and anything earlier won't work regardless of what we do on the Functions side

Thank you @ejizba for the clarification.

**Comment by michaelpeng36** [comment]
Closing, as this affected the host's ability to start the PowerShell worker.

**Pull request closed without merging**
